In [53]:
import pandas as pd
df = pd.read_csv('credit_risk_dataset.csv')
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [54]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [55]:
import sqlite3
conn = sqlite3.connect('credit_risk.db')
# now we need to form an actual SQL database
df.to_sql('credit_risk', conn, if_exists='replace', index=False)

32581

In [56]:
query = """
SELECT COUNT(*)
FROM credit_risk
WHERE person_age > 100
"""
query_results = pd.read_sql_query(query, conn)
query_results

   COUNT(*)
0         5

In [57]:
query = """
SELECT *
FROM credit_risk
WHERE person_age <= 100
"""
df_clean = pd.read_sql_query(query, conn)
df_clean

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32571,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32572,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32573,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32574,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32575,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [58]:
df_clean.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32576.000000,3.257600e+04,31681.000000,32576.000000,29461.000000,32576.000000,32576.000000,32576.000000
mean,27.718044,6.588214e+04,4.789527,9589.117755,11.011547,0.218197,0.170212,5.803966
std,6.204990,5.253499e+04,4.142706,6321.886846,3.240623,0.413029,0.106778,4.053791
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,94.000000,2.039784e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [59]:
# we cleaned credit_risk and now we have a new dataset (df_clean)
# dataset to sql
df_clean.to_sql('credit_risk_clean', conn, if_exists='replace', index=False)

32576

In [60]:
query = """
SELECT *
FROM credit_risk_clean
WHERE (person_age - person_emp_length) >= 16
"""
df_clean_2 = pd.read_sql_query(query, conn)
df_clean_2

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
...,...,...,...,...,...,...,...,...,...,...,...,...
30936,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
30937,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
30938,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
30939,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
30940,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [61]:
df_clean_2.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,30941.000000,3.094100e+04,30941.000000,30941.000000,27973.000000,30941.000000,30941.000000,30941.000000
mean,27.799716,6.646148e+04,4.661517,9642.978572,11.044340,0.215765,0.169449,5.847096
std,6.245086,5.305258e+04,3.965291,6338.458340,3.226868,0.411359,0.106278,4.080277
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.900000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.570000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12375.000000,13.480000,0.000000,0.230000,8.000000
max,94.000000,2.039784e+06,41.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [62]:
# we cleaned df_clean and now, we have new dataset (df_clean_2)
# dataset to sql
df_clean_2.to_sql('credit_risk_clean_2', conn, if_exists='replace', index=False)

30941

In [63]:
query = """
SELECT loan_grade,
AVG(loan_status) AS default_rate,
COUNT(*) AS loan_count
FROM credit_risk_clean_2
GROUP BY loan_grade
"""
df_loan_grade = pd.read_sql_query(query, conn)
df_loan_grade

  loan_grade  default_rate  loan_count
0          A      0.095309       10104
1          B      0.159011        9949
2          C      0.201971        6189
3          D      0.591432        3478
4          E      0.648387         930
5          F      0.701299         231
6          G      0.983333          60

In [64]:
query = """
SELECT loan_intent,
AVG(loan_status) AS default_rate,
COUNT(*)AS loan_count
FROM credit_risk_clean_2
GROUP BY loan_intent
"""
df_loan_intent = pd.read_sql_query(query, conn)
df_loan_intent

         loan_intent  default_rate  loan_count
0  DEBTCONSOLIDATION      0.282248        4946
1          EDUCATION      0.169644        6101
2    HOMEIMPROVEMENT      0.256745        3447
3            MEDICAL      0.265547        5773
4           PERSONAL      0.194561        5258
5            VENTURE      0.148449        5416

In [65]:
query = """
SELECT person_home_ownership,
AVG(loan_status) AS default_rate,
COUNT(*) as loan_count
FROM credit_risk_clean_2
GROUP BY person_home_ownership
"""
df_person_home_ownership = pd.read_sql_query(query, conn)
df_person_home_ownership

  person_home_ownership  default_rate  loan_count
0              MORTGAGE      0.124853       12719
1                 OTHER      0.311321         106
2                   OWN      0.069658        2340
3                  RENT      0.310091       15776

In [66]:
import statsmodels.formula.api as smf
model = smf.logit('loan_status ~ person_income + loan_amnt + C(loan_grade)', data = df_clean_2).fit()
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.392256
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:            loan_status   No. Observations:                30941
Model:                          Logit   Df Residuals:                    30932
Method:                           MLE   Df Model:                            8
Date:                Mon, 21 Sep 2026   Pseudo R-squ.:                  0.2478
Time:                        00:45:17   Log-Likelihood:                -12137.
converged:                       True   LL-Null:                       -16136.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -1.2069      0.048    -25.119      0.000      -1.301      -1.113
C(loan_grade)[T.B]     0.4548      0.045     10.018      0.000       0.366       0.544
C(loan_grade)[T.C]     0.7784      0.048     16.105      0.000       0.684       0.873
C(loan_grade)[T.D]     2.6565      0.052     50.784      0.000       2.554       2.759
C(loan_grade)[T.E]     2.9968      0.087     34.594      0.000       2.827       3.167
C(loan_grade)[T.F]     3.3125      0.175     18.927      0.000       2.969       3.655
C(loan_grade)[T.G]     8.3175      1.647      5.051      0.000       5.090      11.545
person_income      -3.586e-05      8e-07    -44.829      0.000   -3.74e-05   -3.43e-05
loan_amnt              0.0001   3.01e-06     34.670      0.000    9.86e-05       0.000
======================================================================================

In [67]:
# now this is in log - we have to raise it e^(something)
import numpy as np
np.exp(model.params)

Intercept                0.299118
C(loan_grade)[T.B]       1.575819
C(loan_grade)[T.C]       2.178015
C(loan_grade)[T.D]      14.246465
C(loan_grade)[T.E]      20.021092
C(loan_grade)[T.F]      27.452674
C(loan_grade)[T.G]    4094.774529
person_income            0.999964
loan_amnt                1.000105
dtype: float64

In [68]:
# PHASE 2 - SCIKIT LEARN PREDICTION
# Design Matrix formation-ish
X = df_clean_2.drop(columns = 'loan_status')
y = df_clean_2['loan_status']
# print(X)
type(y)

pandas.core.series.Series

In [69]:
# fix beacuse X has null values
# find where null values are
X.isnull().sum()
# fill the null values with median OR alternatively we could have dropped this
X['loan_int_rate'] = X['loan_int_rate'].fillna(X['loan_int_rate'].median())
# X = X.dropna()
# y = y.loc[X.index]

In [70]:
# now we are going to make dummy variables for all the categorical variables
# we are going to drop the first one - keep it as baseline to avoid multicollinearity
X = pd.get_dummies(X, drop_first = True)
X

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G,cb_person_default_on_file_Y
0,21,9600,5.0,1000,11.14,0.10,2,False,True,False,...,False,False,False,True,False,False,False,False,False,False
1,25,9600,1.0,5500,12.87,0.57,3,False,False,False,...,True,False,False,False,True,False,False,False,False,False
2,23,65500,4.0,35000,15.23,0.53,2,False,False,True,...,True,False,False,False,True,False,False,False,False,False
3,24,54400,8.0,35000,14.27,0.55,4,False,False,True,...,True,False,False,False,True,False,False,False,False,True
4,21,9900,2.0,2500,7.14,0.25,2,False,True,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30936,57,53000,1.0,5800,13.16,0.11,30,False,False,False,...,False,True,False,False,True,False,False,False,False,False
30937,54,120000,4.0,17625,7.49,0.15,19,False,False,False,...,False,True,False,False,False,False,False,False,False,False
30938,65,76000,3.0,35000,10.99,0.46,28,False,False,True,...,False,False,False,True,False,False,False,False,False,False
30939,56,150000,5.0,15000,11.48,0.10,26,False,False,False,...,False,True,False,True,False,False,False,False,False,False
30940,66,42000,2.0,6475,9.99,0.15,30,False,False,True,...,True,False,False,True,False,False,False,False,False,False

In [71]:
# split the data 80/20 to train and split
# using 42 as seed - from "The Hitchhiker's Guide To Galaxy"
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.2, random_state = 42)
X_train
# y_train
# X_test
# y_test

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G,cb_person_default_on_file_Y
314,26,168750,10.0,24250,12.87,0.14,3,False,False,True,...,True,False,False,False,True,False,False,False,False,True
29286,37,33000,0.0,10000,5.99,0.30,11,False,False,True,...,False,False,True,False,False,False,False,False,False,False
25535,27,50000,1.0,15000,13.16,0.30,9,False,False,True,...,False,False,True,False,True,False,False,False,False,False
26764,30,130000,14.0,7000,9.91,0.05,9,False,False,False,...,False,False,True,True,False,False,False,False,False,False
20588,28,25000,0.0,7000,6.92,0.28,6,False,False,True,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29802,42,13200,4.0,2500,10.99,0.19,14,False,False,True,...,False,False,False,False,True,False,False,False,False,True
5390,26,83004,7.0,5450,7.90,0.07,4,False,False,True,...,False,False,False,False,False,False,False,False,False,False
860,22,43000,4.0,18550,11.83,0.43,4,False,False,True,...,False,False,False,True,False,False,False,False,False,False
15795,24,72000,8.0,5000,6.03,0.07,4,False,False,False,...,False,True,False,False,False,False,False,False,False,False
23654,31,35000,6.0,11700,13.06,0.33,9,False,False,True,...,True,False,False,False,True,False,False,False,False,False

In [78]:
from sklearn.preprocessing import StandardScaler
# new concept - have to review scaling issues
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [79]:
# Using logistic regression to predict
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
# note/ recieved an error because matrix X had null values - went back to when we created X and y to fix

LogisticRegression()